### ISSUE TITLE
No more validation?

### ISSUE THREAD

**Issue by rmosolgo** [facebook/emitter#14]
Hi, this is really a "just curious" question! I remember reading about this project in the spring and one thing that really stood out was "event validation", the way you could whitelist events upfront to cause loud failures if the emitter was misused later on. 

But, it seems like that feature has been removed. Why did you decide to remove it? Was it less helpful in practice than on paper? Or did it have unintended consequences?

**Comment by kyldvs** [comment]
I think it mostly fell under the category of "Less helpful in practice than on paper". With the latest update we were basically trimming the project to what we used internally at FB so would could be confident that what is out in the world is actually something we are using and testing regularly.

**Comment by rmosolgo** [comment]
Cool, thanks for the info!
