### ISSUE TITLE
Naming collision detected

### ISSUE THREAD

**Issue by rokugou** [facebook/emitter#20]
react packager
```
Error: Naming collision detected: /Users/roku/Documents/r/on/node_modules/react-native/node_modules/fbjs/lib/camelize.js collides with /Users/roku/Documents/r/on/node_modules/fbemitter/node_modules/fbjs/lib/camelize.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/roku/Documents/r/on/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/roku/Documents/r/on/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/roku/Documents/r/on/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
~
```

i am using
```
    "react-native": "^0.18.0-rc",
    "fbemitter": "2.0.1",
```

**Comment by zpao** [comment]
cc @ide since he's been deeper on this recently. I think the solution will likely be just `rm -rf node_modules && npm install` but there might be something else, I'm not familiar with how all these fbjs pieces are fitting together.

**Comment by ide** [comment]
We use npm 3 to dedupe the fbjs dependency.

**Comment by zpao** [comment]
So does working with RN now require npm 3?

**Comment by ide** [comment]
RN works with npm 2 -- we recommend it in fact -- but I'm not sure if npm 3 is required for fbemitter compatibility. I've been using npm 3 to see how well it works (it's been mostly OK but I think it has a couple bugs).

That recent series of fbjs patches might allow for multiple copies of fbjs under node_modules. They should land in react-native soon, and will likely go out with 0.19-rc in two weeks.

Anyway @zpao I think you can close this issue. It's not an issue with fbemitter.

**Comment by adriansprod** [comment]
Same here since update to R18

…/node_modules/flux/node_modules/fbjs/flow/include/camelize.js collides with …./node_modules/react-native/node_modules/fbjs/lib/camelize.js
