### ISSUE TITLE
ES6 module loading: Cannot find module ./lib/BaseEventEmitter

### ISSUE THREAD

**Issue by andreassolberg** [facebook/emitter#23]
I'm trying to load the module using ES6 with babelify.

I get the error:

`Cannot find module './lib/BaseEventEmitter' from ... `

I install the module using npm

I load the module like this:

`import {EventEmitter} from 'fbemitter';`

I see in package.js, that it points main to index.js. And index.js `require('./lib/BaseEventEmitter')`.

The `lib` directory is not present. May be it should say `src`?

**Comment by zpao** [comment]
The compiled project has a `lib/` path. The published npm package has that so this should be working. If you don't have a lib directory in your installed copied, you may have installed from github directly which we don't support.
