### ISSUE TITLE
Handle all events

### ISSUE THREAD

**Issue by Luchanso** [facebook/emitter#31]
Hi, can you add API for handling all events like a
```js
emmiterNamespace.addListener('*', () => {...});
```

**Comment by Luchanso** [comment]
It's need for handling all event by namespace, for example:
I have button event emmiter: `btnEmmiter`
And I want logging all events from button `btnEmmiter.addListener('*', log);`

**Comment by kyldvs** [comment]
It should be easy enough to extend the base emitter to get this functionality without us needing to expose an explicit method for it. This API has been fairly stable and I'm not convinced this is necessarily a pattern to encourage. I'd suggest you go ahead with extending the base emitter like this (depending on your specific needs the implementation may need to vary a bit):

```
class AllEmitter extends EventEmitter {
  constructor() {
    super();
    this._allListeners = [];
  }

  addAllListener(fn) {
    this._allListeners.push(fn);
  }

  emit(...args) {
    this._allListeners.forEach(fn => fn(...args));
    super.emit(...args);
  }
}
```
