### ISSUE TITLE
Stop using PhantomJS for testing

### ISSUE THREAD

**Issue by zpao** [facebook/emitter#4]
Just use jest.

We already do that now, but we still have a bunch of code in there to use phantomjs via grunt.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyldvs** [comment]
can be closed with #9 now
