### ISSUE TITLE
Ship to npm

### ISSUE THREAD

**Issue by zpao** [facebook/emitter#7]
We don't right now but we probably should. That way Flux can make use of this instead of the node emitter.

- [x] don't ship any `bin`s
- [x] clean up dependencies
- [ ] figure out public API (`require('fbemitter')` gives you what?)

**Comment by eklipse2k8** [comment]
yes please ;)

**Comment by umidbekkarimov** [comment]
+1

And, i guess this should be good

````javascript
var {EventEmitter, EventHolder, EventEmitterWithHolding} = require('fbemitter');

**Comment by kyldvs** [comment]
This would be nice to have soon :)

**Comment by kyldvs** [comment]
done, https://www.npmjs.com/package/fbemitter :)
